# Secrets configuration file

email_username: "your_email@example.com"
email_password: "your_email_password"
firebase_api_key: "your_firebase_api_key"
telegram_api_token: "your-telegram-bot-api-token"
aws_access_key: "your_aws_access_key"
aws_secret_key: "your_aws_secret_key"
google_drive_folder_id: "your_google_drive_folder_id"
nextcloud_username: "your_nextcloud_username"
nextcloud_password: "your_nextcloud_password"
aes_encryption_key: "your_generated_aes_key"

